#!/bin/bash

# Ordnerpfad
folder_path="./sounds"

echo "Generated by fileinput.sh script."

# Array-Start
echo "let soundsFiles = [" > soundsFiles.js
# Durch alle Dateien und Unterordner gehen
for dir in "$folder_path"/*/; do
  if [ -d "$dir" ]; then
    # Ordnername
    foldername=$(basename "$dir")
    echo "    // Dateien in Ordner: $foldername" >> soundsFiles.js
    # Alle Dateien im Unterordner
    for file in "$dir"*; do
      if [ -f "$file" ]; then
        # Dateiname mit Ordnername kombinieren
        filename="$foldername/$(basename "$file")"
        echo "    \"$filename\"," >> soundsFiles.js
      fi
    done
  fi
done

# Array-Ende (letzte Zeile entfernen und abschließen)
sed -i '' '$ s/,$//' soundsFiles.js
echo "]" >> soundsFiles.js
